### PR TITLE
Make Statermons Offical

### PR DESCRIPTION
**Pull request by HoeenCoder**
Make Startermons tier offical, and remove other tiers.

### CODE REVIEW

**Comment by anurudhp** [comment]
lol. name typo?? or is it really hoeen**herp**

**Comment by anurudhp** [comment]
bad indenting, we dont use spaces. we use tabs.
Please test the code using `npm test` before submitting a pull req.

**Comment by HoeenCoder** [comment]
yes, name typo

mobile can't use tab :(

**Comment by anurudhp** [comment]
done in e47a57200bace35d47473859938376c7c71272d0

**Comment by HoeenCoder** [comment]
did you edit statermons so its setup as offical?

**Pull request closed without merging**
